#! /usr/bin/perl

# fake replacement for dpkg-query to use in unit tests

# rule: 

if ($ARGV[0] eq '--search')
  {
    my $file = $ARGV[1];
    my $pkg = 'TODO'; # TODO: somehow determine pkg name from filename
    print "$pkg: $file\n";
  }
elsif ($ARGV[0] eq '-W'
    && $ARGV[1] eq '--showformat'
    && $ARGV[2] eq '\${Version} ')
  {
    my $pkg = $ARGV[3];
    my $version = 'TODO'; # TODO: somehow determine pkg version 
    print "$version ";
  }
else
  {
    exit (1);
  }

0;
